# Generated by Django 3.2.4 on 2021-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('SEC', 'Secretariat'), ('DIR', 'Directorate')], max_length=3),
        ),
    ]
