# Generated by Django 3.2.4 on 2021-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
