# Generated by Django 3.2.4 on 2021-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallery_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='at_home',
            field=models.BooleanField(default=False),
        ),
    ]
