# Generated by Django 3.2.4 on 2021-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211211_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publish_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='info',
            new_name='descripton',
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('SEC', 'Secretariat'), ('DIR', 'Directorate')], default='SEC', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
