# Generated by Django 3.2.4 on 2021-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211211_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('trigger_at', models.DateTimeField()),
                ('triggered', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('SECRETARIAT', 'Secretariat'), ('DIRECTORATE', 'Directorate')], default='SECRETARIAT', max_length=11),
        ),
    ]
