# Generated by Django 3.2.4 on 2021-12-17 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recent_alternate_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='alternate_text',
            field=models.CharField(blank=True, default=uuid.UUID('f155a662-62d5-44cc-899c-8ccf5415a6ca'), max_length=50, null=True),
        ),
    ]
